# Generated by Django 4.2.1 on 2023-06-05 23:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
